/**
 * Created by Mahmoud on 10/01/2018.
 */

/**
 * Method that takes an Array of the size n and returns a two dimensional Array of the size [n+1][n+1]
 * @param arr is an Array of the size n
 * @returns {Array} of the size [n+1][n+1] that represent the multiplication matrix generated by multiplying the input array by itself
 */
function generateMultiplicationMatrix(arr){

    // Create variable n that holds the length of the input array
    var n = arr.length;

    // Create matrix Array, a multi dimensional Array of the size [n+1][n+1]
    var matrix = new Array(n+1);
    for (var i = 0; i < n+1; i++) {
        matrix[i] = new Array(n+1);
    }

    // Set the values of the multiplication matrix
    // The top row and left column hold the values from the input array
    for(var i = -1; i < n; i++) {
        for(var j = -1; j < n; j++) {
            if( i == -1 && j==-1 ) {
                matrix[i+1][j+1]= "*";
            }
            else if( i == -1 && j!=-1 ) {
                matrix[i+1][j+1]= arr[j];
            }
            else if(j==-1 && i!=-1) {
                matrix[i+1][j+1]= arr[i];
            }
            else {
                matrix[i+1][j+1] = arr[i] * arr[j];
            }
        }
    }
    return matrix;
};

/**
 * Generate an HTML table with the values of the input array
 * @param matrix is a two dimensional array
 * @returns html string: html table holds the values of the input array
 */
function printMatrix(matrix) {
    // output variable holds the html structure of the output table
    // color_td holds the cells background color
    var output, color_td;

    output = "<table border='1px' cellspacing='10px' cellpadding='10px' style='padding: 10px; margin-top: 10px'>";
    for(var i = 0; i < matrix.length; i++) {
        output+= "<tr style='height:30px;'>";
        for(var j = 0; j < matrix[i].length; j++) {
            // dark background color for marking the top row and the left column
            if( i == 0 || j==0 )
                color_td = "#ccc";
            else
                color_td = "#fff";
            output+= "<td style='width:30px;background-color:" + color_td + ";text-align: center;'>" + matrix[i][j] + "</td>";
        }
        output+="</tr>";
    }
    output+= "</table>";
    return output;
};
