/**
 * Created by Mahmoud on 10/01/2018.
 */

/**
 * Method that takes an Array of the size n and returns a two dimensional Array of the size [n+1][n+1]
 * @param arr is an Array of the size n
 * @returns {Array} of the size [n+1][n+1] that represent the multiplication matrix generated by multiplying the input array by itself
 */
function generateMultiplicationMatrix(arr){

    // Create variable n that holds the length of the input array
    var n = arr.length;

    // Create matrix Array, a multi dimensional Array of the size [n+1][n+1]
    var matrix = new Array(n+1);
    for (var i = 0; i < n+1; i++) {
        matrix[i] = new Array(n+1);
    }

    // Set the values of the multiplication matrix
    // The top row and left column hold the values from the input array
    for(var i = -1; i < n; i++) {
        for(var j = -1; j < n; j++) {
            if( i == -1 && j==-1 ) {
                matrix[i+1][j+1]= "*";
            }
            else if( i == -1 && j!=-1 ) {
                matrix[i+1][j+1]= arr[j];
            }
            else if(j==-1 && i!=-1) {
                matrix[i+1][j+1]= arr[i];
            }
            else {
                matrix[i+1][j+1] = arr[i] * arr[j];
            }
        }
    }
    return matrix;
}
